<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AdminMenu;

class AdminMenuSeeder extends Seeder
{
    /**
     * 관리자 메뉴 데이터를 시드합니다.
     */
    public function run(): void
    {
        // 기존 데이터 삭제
        AdminMenu::query()->delete();

        // 최신 데이터베이스 데이터를 기반으로 생성
        $menus = [
            [
                'id' => 1,
                'parent_id' => null,
                'name' => '대시보드',
                'url' => '/backoffice',
                'icon' => 'fa-tachometer-alt',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-09-23 07:22:04',
                'permission_key' => null,
            ],
            [
                'id' => 3,
                'parent_id' => 6,
                'name' => '기본설정',
                'url' => '/backoffice/setting',
                'icon' => null,
                'order' => 1,
                'is_active' => 0,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-10-15 01:34:59',
                'permission_key' => null,
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'name' => '기본설정',
                'url' => null,
                'icon' => 'fa-file-alt',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-09-23 07:22:12',
                'permission_key' => null,
            ],
            [
                'id' => 8,
                'parent_id' => 21,
                'name' => '팝업 관리',
                'url' => '/backoffice/popups',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-09-29 06:11:39',
                'permission_key' => null,
            ],
            [
                'id' => 10,
                'parent_id' => 19,
                'name' => '공지관리',
                'url' => '/backoffice/board-posts/notices',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-06 12:44:51',
                'updated_at' => '2025-09-30 00:51:18',
                'permission_key' => null,
            ],
            [
                'id' => 17,
                'parent_id' => 19,
                'name' => '소식관리',
                'url' => '/backoffice/board-posts/gallerys',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-08-21 07:20:49',
                'updated_at' => '2025-09-30 00:51:25',
                'permission_key' => null,
            ],
            [
                'id' => 18,
                'parent_id' => 21,
                'name' => '배너 관리',
                'url' => '/backoffice/banners',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-08-24 09:35:23',
                'updated_at' => '2025-09-29 06:11:37',
                'permission_key' => null,
            ],
            [
                'id' => 19,
                'parent_id' => null,
                'name' => '게시판관리',
                'url' => null,
                'icon' => 'fa-chart-bar',
                'order' => 7,
                'is_active' => 1,
                'created_at' => '2025-08-24 09:36:13',
                'updated_at' => '2025-09-23 07:22:02',
                'permission_key' => null,
            ],
            [
                'id' => 20,
                'parent_id' => 6,
                'name' => '관리자 관리',
                'url' => '/backoffice/admins',
                'icon' => '',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-09-19 00:19:49',
                'updated_at' => '2025-09-22 07:46:49',
                'permission_key' => null,
            ],
            [
                'id' => 21,
                'parent_id' => null,
                'name' => '홈페이지관리',
                'url' => null,
                'icon' => 'fa-home',
                'order' => 8,
                'is_active' => 1,
                'created_at' => '2025-09-23 07:20:08',
                'updated_at' => '2025-09-23 07:22:02',
                'permission_key' => null,
            ],
            [
                'id' => 22,
                'parent_id' => null,
                'name' => '기업정보관리',
                'url' => null,
                'icon' => 'fa-users',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-23 07:21:13',
                'updated_at' => '2025-09-23 07:22:12',
                'permission_key' => null,
            ],
            [
                'id' => 23,
                'parent_id' => null,
                'name' => '사업분야관리',
                'url' => null,
                'icon' => 'fa-file',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-09-23 07:21:26',
                'updated_at' => '2025-09-23 07:22:12',
                'permission_key' => null,
            ],
            [
                'id' => 24,
                'parent_id' => null,
                'name' => '채용관리',
                'url' => null,
                'icon' => 'fa-user',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-09-23 07:21:42',
                'updated_at' => '2025-09-23 07:22:12',
                'permission_key' => null,
            ],
            [
                'id' => 25,
                'parent_id' => 22,
                'name' => '인사말관리',
                'url' => '/backoffice/board-posts/greetings',
                'icon' => '',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-23 07:29:41',
                'updated_at' => '2025-09-23 13:14:56',
                'permission_key' => null,
            ],
            [
                'id' => 26,
                'parent_id' => 22,
                'name' => '국문연혁관리',
                'url' => '/backoffice/board-posts/company_history_ko',
                'icon' => '',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-09-23 08:14:55',
                'updated_at' => '2025-09-23 13:14:56',
                'permission_key' => null,
            ],
            [
                'id' => 27,
                'parent_id' => 22,
                'name' => '영문연혁관리',
                'url' => '/backoffice/board-posts/company_history_en',
                'icon' => '',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-09-23 08:14:55',
                'updated_at' => '2025-09-23 13:14:56',
                'permission_key' => null,
            ],
            [
                'id' => 28,
                'parent_id' => 22,
                'name' => '품질/환경경영관리',
                'url' => '/backoffice/board-posts/quality_environment',
                'icon' => '',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-23 08:14:55',
                'updated_at' => '2025-09-23 13:14:56',
                'permission_key' => null,
            ],
            [
                'id' => 29,
                'parent_id' => 22,
                'name' => '안전/보건경영관리',
                'url' => '/backoffice/board-posts/safety_health',
                'icon' => '',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-09-23 08:14:55',
                'updated_at' => '2025-09-23 13:14:56',
                'permission_key' => null,
            ],
            [
                'id' => 30,
                'parent_id' => 23,
                'name' => 'PDI브랜드관리',
                'url' => '/backoffice/board-posts/pdi_brands',
                'icon' => '',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-26 13:54:20',
                'updated_at' => '2025-09-26 13:54:20',
                'permission_key' => null,
            ],
            [
                'id' => 31,
                'parent_id' => 23,
                'name' => '항만물류협력사관리',
                'url' => '/backoffice/board-posts/logistics_partners',
                'icon' => '',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-09-26 13:54:58',
                'updated_at' => '2025-09-26 13:54:58',
                'permission_key' => null,
            ],
            [
                'id' => 32,
                'parent_id' => 23,
                'name' => '사업문의내용 관리',
                'url' => '/backoffice/board-posts/business_inquiries',
                'icon' => '',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-09-26 13:55:47',
                'updated_at' => '2025-09-26 13:55:47',
                'permission_key' => null,
            ],
            [
                'id' => 33,
                'parent_id' => 24,
                'name' => '채용관리',
                'url' => '/backoffice/board-posts/recruitments',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-26 14:01:32',
                'updated_at' => '2025-09-26 14:01:32',
                'permission_key' => null,
            ],
            [
                'id' => 34,
                'parent_id' => 19,
                'name' => 'Contact us 관리',
                'url' => '/backoffice/board-posts/contact_us',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-09-29 04:53:42',
                'updated_at' => '2025-09-29 04:53:47',
                'permission_key' => null,
            ],
            [
                'id' => 35,
                'parent_id' => 21,
                'name' => 'Family Site 관리',
                'url' => '/backoffice/board-posts/family_sites',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-09-29 06:10:33',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
            [
                'id' => 36,
                'parent_id' => 21,
                'name' => '윤리경영',
                'url' => '/backoffice/board-posts/business_ethics',
                'icon' => null,
                'order' => 7,
                'is_active' => 1,
                'created_at' => '2025-09-29 06:10:59',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
            [
                'id' => 37,
                'parent_id' => 21,
                'name' => '이메일 무단수집거부',
                'url' => '/backoffice/board-posts/email_rejection',
                'icon' => null,
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-09-29 06:11:16',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
            [
                'id' => 38,
                'parent_id' => 21,
                'name' => '개인정보처리방침',
                'url' => '/backoffice/board-posts/privacy_policy',
                'icon' => null,
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2025-09-29 06:11:31',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
            [
                'id' => 39,
                'parent_id' => 23,
                'name' => '사업문의내용 관리(영문)',
                'url' => '/backoffice/board-posts/business_inquiries_eng',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-10-20 05:37:52',
                'updated_at' => '2025-10-20 05:40:30',
                'permission_key' => null,
            ],
            [
                'id' => 40,
                'parent_id' => 19,
                'name' => 'Contact us 관리(영문)',
                'url' => '/backoffice/board-posts/contact_us_eng',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2025-10-20 05:37:52',
                'updated_at' => '2025-10-20 05:37:52',
                'permission_key' => null,
            ],
            [
                'id' => 41,
                'parent_id' => 21,
                'name' => '이메일 무단수집거부(영문)',
                'url' => '/backoffice/board-posts/email_rejection_eng',
                'icon' => null,
                'order' => 8,
                'is_active' => 1,
                'created_at' => '2025-10-20 05:37:52',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
            [
                'id' => 42,
                'parent_id' => 21,
                'name' => '윤리경영(영문)',
                'url' => '/backoffice/board-posts/business_ethics_eng',
                'icon' => null,
                'order' => 9,
                'is_active' => 1,
                'created_at' => '2025-10-20 05:37:52',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
            [
                'id' => 43,
                'parent_id' => 21,
                'name' => '개인정보처리방침(영문)',
                'url' => '/backoffice/board-posts/privacy_policy_eng',
                'icon' => null,
                'order' => 10,
                'is_active' => 1,
                'created_at' => '2025-10-20 05:37:52',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
            [
                'id' => 44,
                'parent_id' => 21,
                'name' => '안전/보건경영 메일 관리',
                'url' => '/backoffice/board-posts/safety_health_mail',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-10-20 05:56:17',
                'updated_at' => '2025-10-20 05:56:35',
                'permission_key' => null,
            ],
        ];

        // parent_id가 null인 메뉴들을 먼저 생성
        $parentMenus = array_filter($menus, function($menu) {
            return $menu['parent_id'] === null;
        });
        
        foreach ($parentMenus as $menu) {
            AdminMenu::create($menu);
        }
        
        // 그 다음에 자식 메뉴들을 생성
        $childMenus = array_filter($menus, function($menu) {
            return $menu['parent_id'] !== null;
        });
        
        foreach ($childMenus as $menu) {
            AdminMenu::create($menu);
        }
    }
}