<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Board;

class BoardSeeder extends Seeder
{
    /**
     * 게시판 데이터를 시드합니다.
     */
    public function run(): void
    {
        // 기존 데이터 삭제 (하드 삭제)
        Board::query()->forceDelete();

        // 최신 데이터베이스 데이터를 기반으로 생성
        $boards = [
            [
                'id' => 1,
                'name' => '공지사항',
                'slug' => 'notices',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 1,
                'is_single_page' => 0,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-23 06:55:06',
                'updated_at' => '2025-09-23 06:55:06',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 2,
                'name' => '갤러리',
                'slug' => 'gallerys',
                'description' => null,
                'skin_id' => 2,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-23 06:55:06',
                'updated_at' => '2025-09-23 06:55:06',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 3,
                'name' => '인사말',
                'slug' => 'greetings',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 1,
                'is_single_page' => 1,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-23 07:34:15',
                'updated_at' => '2025-09-23 08:28:31',
                'deleted_at' => null,
                'custom_fields_config' => '[{"name": "greeting_ko", "type": "editor", "label": "인사말 국문", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "greeting_en", "type": "editor", "label": "인사말 영문", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "ceo_message_ko", "type": "text", "label": "대표이사 국문", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "ceo_message_en", "type": "text", "label": "대표이사 영문", "options": null, "required": false, "max_length": null, "placeholder": null}]',
            ],
            [
                'id' => 4,
                'name' => '국문연혁관리',
                'slug' => 'company_history_ko',
                'description' => 'aas3',
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 1,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-23 13:19:47',
                'updated_at' => '2025-09-29 08:23:33',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 5,
                'name' => '영문연혁관리',
                'slug' => 'company_history_en',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 1,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-23 13:19:47',
                'updated_at' => '2025-09-23 14:09:29',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 6,
                'name' => '품질/환경경영관리',
                'slug' => 'quality_environment',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-23 13:19:47',
                'updated_at' => '2025-09-29 00:03:49',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 7,
                'name' => '안전/보건경영관리',
                'slug' => 'safety_health',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-23 13:19:47',
                'updated_at' => '2025-09-29 00:03:56',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 8,
                'name' => 'PDI브랜드관리',
                'slug' => 'pdi_brands',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 1,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-26 13:54:20',
                'updated_at' => '2025-09-29 00:05:31',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 9,
                'name' => '항만물류협력사관리',
                'slug' => 'logistics_partners',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 1,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-26 13:54:58',
                'updated_at' => '2025-09-29 00:05:43',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 10,
                'name' => '사업문의내용 관리',
                'slug' => 'business_inquiries',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 1,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-26 13:55:47',
                'updated_at' => '2025-09-29 02:26:33',
                'deleted_at' => null,
                'custom_fields_config' => '[{"name": "pdi_tel", "type": "text", "label": "PDI 문의 - TEL", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "pdi_mail", "type": "text", "label": "PDI 문의 - MAIL", "required": true, "placeholder": "이메일을 입력하세요"}, {"name": "logistics_tel", "type": "text", "label": "물류 문의 - TEL", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "logistics_mail", "type": "text", "label": "물류 문의 - MAIL", "required": true, "placeholder": "이메일을 입력하세요"}, {"name": "special_vehicle_tel", "type": "text", "label": "특수차 문의 - TEL", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "special_vehicle_mail", "type": "text", "label": "특수차 문의 - MAIL", "required": true, "placeholder": "이메일을 입력하세요"}]',
            ],
            [
                'id' => 11,
                'name' => '채용관리',
                'slug' => 'recruitments',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 1,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 1,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-26 14:01:32',
                'updated_at' => '2025-09-29 04:02:18',
                'deleted_at' => null,
                'custom_fields_config' => '[{"name": "tel", "type": "text", "label": "TEL", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "mail", "type": "text", "label": "MAIL", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "link", "type": "text", "label": "링크주소", "options": null, "required": false, "max_length": null, "placeholder": null}]',
            ],
            [
                'id' => 12,
                'name' => 'Contact us 관리',
                'slug' => 'contact_us',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 1,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-29 04:46:11',
                'updated_at' => '2025-09-29 04:48:09',
                'deleted_at' => null,
                'custom_fields_config' => '[{"name": "hr_manager", "type": "text", "label": "인사 담당자 - 이름", "required": true, "placeholder": "이름을 입력하세요"}, {"name": "hr_phone", "type": "text", "label": "인사 담당자 - 전화", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "hr_email", "type": "email", "label": "인사 담당자 - E-MAIL", "required": true, "placeholder": "이메일을 입력하세요"}, {"name": "finance_manager", "type": "text", "label": "재무 담당자 - 이름", "required": true, "placeholder": "이름을 입력하세요"}, {"name": "finance_phone", "type": "text", "label": "재무 담당자 - 전화", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "finance_email", "type": "email", "label": "재무 담당자 - E-MAIL", "required": true, "placeholder": "이메일을 입력하세요"}, {"name": "pdi_manager1", "type": "text", "label": "부산 PDI담당 - 이름 1", "required": true, "placeholder": "이름을 입력하세요"}, {"name": "pdi_phone1", "type": "text", "label": "부산 PDI담당 - 전화 1", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "pdi_manager2", "type": "text", "label": "부산 PDI담당 - 이름 2", "required": true, "placeholder": "이름을 입력하세요"}, {"name": "pdi_phone2", "type": "text", "label": "부산 PDI담당 - 전화 2", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "pdi_email", "type": "email", "label": "부산 PDI담당 - E-MAIL", "required": true, "placeholder": "이메일을 입력하세요"}, {"name": "logistics_manager", "type": "text", "label": "부산 물류/항만 - 이름", "required": true, "placeholder": "이름을 입력하세요"}, {"name": "logistics_phone", "type": "text", "label": "부산 물류/항만 - 전화", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "logistics_email", "type": "email", "label": "부산 물류/항만 - E-MAIL", "required": true, "placeholder": "이메일을 입력하세요"}, {"name": "vehicle_manager", "type": "text", "label": "부산 특수차 담당 - 이름", "required": true, "placeholder": "이름을 입력하세요"}, {"name": "vehicle_phone", "type": "text", "label": "부산 특수차 담당 - 전화", "required": true, "placeholder": "전화번호를 입력하세요"}, {"name": "vehicle_email", "type": "email", "label": "부산 특수차 담당 - E-MAIL", "required": true, "placeholder": "이메일을 입력하세요"}]',
            ],
            [
                'id' => 13,
                'name' => 'Family Site 관리',
                'slug' => 'family_sites',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 0,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-29 06:02:48',
                'updated_at' => '2025-09-29 06:09:54',
                'deleted_at' => null,
                'custom_fields_config' => '[{"name": "kor", "type": "text", "label": "한국어", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "eng", "type": "text", "label": "영어", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "url", "type": "text", "label": "URL", "options": null, "required": false, "max_length": null, "placeholder": null}]',
            ],
            [
                'id' => 14,
                'name' => '개인정보처리방침',
                'slug' => 'privacy_policy',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 1,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-29 06:03:05',
                'updated_at' => '2025-09-29 06:14:49',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 15,
                'name' => '이메일 무단수집거부',
                'slug' => 'email_rejection',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 1,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-29 06:03:20',
                'updated_at' => '2025-09-29 06:14:43',
                'deleted_at' => null,
                'custom_fields_config' => null,
            ],
            [
                'id' => 16,
                'name' => '윤리경영',
                'slug' => 'business_ethics',
                'description' => null,
                'skin_id' => 1,
                'is_active' => 1,
                'table_created' => 0,
                'list_count' => 10,
                'enable_notice' => 0,
                'is_single_page' => 1,
                'enable_sorting' => 0,
                'hot_threshold' => 100,
                'permission_read' => 'all',
                'permission_write' => 'all',
                'permission_comment' => 'all',
                'created_at' => '2025-09-29 06:03:32',
                'updated_at' => '2025-09-29 06:49:26',
                'deleted_at' => null,
                'custom_fields_config' => '[{"name": "reporting_rules", "type": "editor", "label": "신고제도 안내", "options": null, "required": false, "max_length": null, "placeholder": null}, {"name": "email", "type": "text", "label": "PLS 이메일", "options": null, "required": true, "max_length": null, "placeholder": null}]',
            ],
        ];

        foreach ($boards as $board) {
            Board::create($board);
        }
    }
}
